-- Schema for the financial_transactions table
CREATE TABLE financial_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    transaction_type TEXT CHECK (transaction_type IN ('income', 'expense')) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    category TEXT,
    description TEXT,
    transaction_date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add index for faster queries on user_id and transaction_date
CREATE INDEX idx_financial_transactions_user_id_date ON financial_transactions(user_id, transaction_date);

-- Schema for the budgets table
CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    category TEXT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    period TEXT CHECK (period IN ('weekly', 'monthly', 'yearly')) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, category, period)
);

-- Add index for faster queries on user_id and category for budgets
CREATE INDEX idx_budgets_user_id_category ON budgets(user_id, category);

-- Add comments to explain the tables and columns
COMMENT ON TABLE financial_transactions IS 'Stores individual financial transactions for users.';
COMMENT ON COLUMN financial_transactions.transaction_type IS 'Type of the transaction, either income or expense.';
COMMENT ON COLUMN financial_transactions.amount IS 'The amount of the transaction.';
COMMENT ON COLUMN financial_transactions.category IS 'User-defined category for the transaction (e.g., Groceries, Salary).';
COMMENT ON COLUMN financial_transactions.transaction_date IS 'The date the transaction occurred.';

COMMENT ON TABLE budgets IS 'Stores user-defined budgets for specific categories and periods.';
COMMENT ON COLUMN budgets.period IS 'The time period for the budget, e.g., weekly, monthly, or yearly.';
COMMENT ON COLUMN budgets.amount IS 'The budgeted amount for the category and period.';
COMMENT ON COLUMN budgets.start_date IS 'The start date of the budget period.';
COMMENT ON COLUMN budgets.end_date IS 'The end date of the budget period.';
