-- Schema for the tech_support_tickets table
CREATE TABLE tech_support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    message TEXT NOT NULL,
    status TEXT CHECK (status IN ('open', 'in_progress', 'closed')) NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add index for faster queries on user_id
CREATE INDEX idx_tech_support_tickets_user_id ON tech_support_tickets(user_id);

-- Add comments to explain the table and columns
COMMENT ON TABLE tech_support_tickets IS 'Stores user-submitted tech support tickets.';
COMMENT ON COLUMN tech_support_tickets.message IS 'The user''s message detailing the technical issue.';
COMMENT ON COLUMN tech_support_tickets.status IS 'The current status of the support ticket.';
